[package]
name = "ctap-hid-fido2"
version = "3.5.0"
authors = ["Robby Cornelissen", "gebo <35388172+gebogebogebo@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

license="MIT"
description="Rust FIDO2 CTAP library"
repository="https://github.com/robby-cornelissen/ctap-hid-fido2"
keywords=["FIDO2","CTAP"]
readme="README.md"

[dependencies]
aes="0.8.1"
anyhow = "1.0"
base64 = "0.21.0"
byteorder = "1.3.4"
cbc = "0.1.2"
hex = "0.4.2"
num = "0.4.0"
pad = "0.1.6"
ring = "0.16.20"
serde = "1.0.126"
serde_cbor = "0.11.1"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0.56"
x509-parser = "0.15"

[dependencies.hidapi]
version = "1.5.0"
default-features = false
features=["linux-static-hidraw"]

[dev-dependencies]
clap = { version = "4.1", features = ["derive"] }
env_logger = "0.10"
log = "0.4"
rpassword = "7.0"

# Used in ctapcli
[target.'cfg(not(linux))'.dev-dependencies]
clipboard = "0.5.0"

[[example]]
name = "ctapcli"

[[example]]
name = "get-info"

[[example]]
name = "reg-auth"

[[example]]
name = "test-with-pin-non-rk"

[[example]]
name = "test-with-pin-rk"

[[example]]
name = "wink"
